apiVersion: v1
kind: Service
metadata:
  name: todo-app
  labels:
    run: todo-app
    spec:
      type: NodePort
      ports:
        - port: 7001
          targetPort: 7000
          protocol: TCP
          name: http
          selector:
            run: todo-app
