apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-frontend
  template:
    metadata:
      labels:
        app: todo-app-frontend
    spec:
      containers:
        - env:
          - name: POSTGRES_HOST
            value: database
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: todo-app-configmap
                key: postgres_db
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: todo-app-secret
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: todo-app-secret
                key: postgres_password
          name: todos
          image: collibra/todo-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 7000
          readinessProbe:
            httpGet:
              path: /api/todo/healthz
              port: 7000
