apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todos
          image: collibra/todo-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 7000
        - name: mydatabase
          image: postgres:alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: postgres_db
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "password"
          volumeMounts:
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: initdb
          configMap:
            name: todo-app-configmap
            items:
              - key: 01_schema.sql
                path: 01_schema.sql
