apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todos
          image: collibra/todo-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 7000
          readinessProbe:
            httpGet:
              path: /api/todo/healthz
              port: 7000
        - name: mydatabase
          image: postgres:alpine
          ports:
            - containerPort: 5432
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - pg_isready -U $POSTGRES_USER
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: postgres_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: todo-app-secret
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-app-secret
                  key: postgres_password
          volumeMounts:
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: initdb
          configMap:
            name: todo-app-configmap
            items:
              - key: 01_schema.sql
                path: 01_schema.sql
