todoApp:
  service:
    app:
      port: 8080
      targetPort: 7000
    database:
      port: 5432
  configMap:
    postgresHost: database
    postgresDb: user
  secret:
    postgresUser: dummy
    postgresPassword: dummy
  frontend:
    image: collibra/todo-app:latest
    containerPort: 7000
  backend:
    containerPort: 5432
