apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: {{ .Values.todoApp.service.database.port }}
  selector:
    app: {{ .Release.Name }}-backend
