apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  postgres_user: {{ .Values.todoApp.secret.postgresUser | b64enc | quote }}
  postgres_password: {{ .Values.todoApp.secret.postgresPassword | b64enc | quote }}
