apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: web
      port: {{ .Values.todoApp.service.app.port }}
      targetPort: {{ .Values.todoApp.service.app.targetPort }}
  selector:
    app: {{ .Release.Name }}-frontend
