apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  postgres_db: {{ .Values.todoApp.configMap.postgresDb | quote }}
  01_schema.sql: |
    DROP TABLE IF EXISTS todos cascade;
    --TODO TABLE
    CREATE TABLE todos(
                          id SERIAL PRIMARY KEY NOT NULL,
                          note TEXT,
                          done BOOLEAN DEFAULT FALSE,
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
