DROP TABLE IF EXISTS todos cascade;

--TODO TABLE
CREATE TABLE todos(
    id SERIAL PRIMARY KEY NOT NULL,
    note TEXT,
    done BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);